letsblockit/letsblockit

- data/filters/search-results.yaml
Basically the search engine's name is DuckDuckGo, not Duck Duck Go
> Duck Duck Go as DuckDuckGo

- data/filters/youtube-shorts.yaml
Shorts now don't show a duration but a logo. Match them on the
accessiblitiy property, but keep the duration matching for now
(the new layout might not be fully rolled out yet)
> youtube-shorts: update rules for new layout

- cmd/render/testdata/expected.txt
- src/filters/list.go
- src/filters/list_test.go
- src/server/list_test.go
uBlock Origin v1.42 supports refresh rates as low as 12 hours now, let's make good use of this, for fixes to ship faster to users.
If the traffic to the server becomes too high in the future, we can revert to a longer period.
> set lists to refresh faster on latest uBO

- data/filters/youtube-cleanup.yaml
I don't know if the default keyword is a good one.
It only show for which purpose you can use this rule
> youtube-cleanup: hide comments based on words

- data/filters/search-results.yaml
- data/pages/view-filter-param-link.hbs
- data/pages/view-filter-param.hbs
- src/db/migrations/0004_duckduckgo_lite.up.sql
- src/filters/filter.go
- Add optional support for filtering results on https://html.duckduckgo.com/html/ and https://lite.duckduckgo.com/lite/, as sub-options when DDG is enabled.
- Set DDG support to off by default to avoid showing these to new users.
- Don't notify the updated params for users who disabled DDG (automatically setting to false).
Fixes #156
> search-results: support lite and html versions of ddg

- data/filters/amazon-products.yaml
Implement product filtering on the Amazon stores worldwide:
- Because simple word matching gives too many false positives, I went with regular expressions here. I added some syntax examples to the page description
- Shipping two presets:
- Amazon devices: Echo, Kindle and Fire TV
- Amazon Basics
For now, the template is in test mode, setting a red background instead of hiding products, to test for false positives. Items can be hidden by removing the `:style(background:red)` at the end of the rules.
You can test it at https://staging.letsblock.it/filters/amazon-products
Fixes https://github.com/letsblockit/letsblockit/issues/146
> amazon-products: add new filter

- data/pages/_layout.hbs
- data/pages/news.hbs
- scripts/run-server.sh
- src/news/markdown.go
- src/news/releases.go
- src/pages/context.go
- src/server/server.go
Users in self-hosted instances will be interested in the full changelog, including changes not relevant to the main instance.
- introduce a new `--official-instance` option, that we'll set on letsblock.it domains
- when that option is true, truncate the changelog and add a link to the github releases page
> display the full changelog on self-hosted instances

- data/filters/youtube-mixes.yaml
- data/filters/youtube-shorts.yaml
- data/filters/youtube-upcoming-videos.yaml
- data/filters/youtube-video-title.yaml
- Update all the relevant youtube filters to work on the subscription page when displayed in list layout. Closes #198 
- Deprecate the old rules for the shorts filter, hopefully the new layout has been rolled out worldwide. I'll revert if someone shouts.
> youtube: expand all filters to support subscriptions list layout

- data/filters/youtube-mixes.yaml
- data/filters/youtube-shorts.yaml
- data/filters/youtube-upcoming-videos.yaml
- data/filters/youtube-video-title.yaml
Revert letsblockit/letsblockit#200 because it causes a regression in the grid view layout: videos are now grouped by date, and one video matching a filter will hide the whole group due to the `ytd-item-section-renderer` rule.
> Revert "youtube: expand all filters to support subscriptions list layout"

- data/filters/youtube-watched.yaml
Add a new filter template to hide videos you've already viewed. Based on an idea from @Markussss.
There is a lot of repetitions in the youtube templates, I need to investigate how to refactor them, as only the leaf selector changes.
Closes https://github.com/letsblockit/letsblockit/issues/205
> youtube-watched: add new template to hide watched videos

- data/filters/youtube-shorts.yaml
- data/filters/youtube-upcoming-videos.yaml
- data/filters/youtube-video-title.yaml
Revisited version of #200, fixing the regression. Only doing the following templates for now:
- shorts
- upcoming
- by title
I am not sure whether mixes/radios can show in subscriptions.
> youtube: expand filters to support subscriptions list layout (second try)

- cmd/server/README.md
- cmd/server/main.go
- src/db/store.go
- src/server/server.go
- Improve the server's `--help` output readability, implements #201 
- Add documentation on how to self-host a Let's Block It instance, with several examples of authentication setup. 
**Note:** the target audience at this point is seasoned users who can figure out the details and read their proxy's documentation and logs. Novice users should use [the official instance](https://letsblock.it) or [the render CLI](https://github.com/letsblockit/letsblockit/blob/main/cmd/render/README.md).
This is why I don't publish a ready-to-use docker-compose (although I have written several for my tests). We can revisit this decision at a later date.
-> [Rendered markdown](https://github.com/letsblockit/letsblockit/blob/selfhost-doc/cmd/server/README.md)
> Document self-hosting of the server

- data/filters/google-search-cleanup.yaml
- src/db/migrations/0006_google-search-cleanup-rich-content.up.sql
Rework the "Cleanup Google search result pages" filters to hopefully address these issues:
- Fixes #219: the "only-results" options breaks News and Shopping pages because it is way too greedy (this is why it was disabled by default). I decided to discontinue it, and replace it by more selective rules. The new "rich-results" is more focused and catches most non-text results while being more reliable. More rules will be added later as we iterate to match more elements
- Fixes #170: pages about cultural works (books, movies...) have a new layout with a `#kp-wp-tab-cont-overview` element, that results in empty pages with the "related-questions", "also-search" and "only-results" options. Impossible to support both layouts with a single rule, so affected rules are duplicated and a variant is …
> google-search-cleanup: revamp filter to work with new design

- data/pages/list-filters.hbs
- src/server/filters.go
- src/server/filters_test.go
- src/server/suite_test.go
The alert is always present, hidden by a cosmetic filter injected in your list. Hidden from screen readers with aria-hidden. The rule has been served for more than a week now, it should be safe to use.
This will be helpful for users installing the list on several browsers, or failing to find the install instructions after resetting their browser / adblocker configuration.
> prompt the user to re-install their list on filter list

- data/filters/google-search-cleanup.yaml
- data/filters/search-results.yaml
Closes #237, make sure google search rules do not apply to other google subdomains.
I could not find a use case that does not have the `www` subdomain, but we will revert this PR if it breaks for some users.
> Restrict Google search rules to www.google.com domain

- src/server/help.go
- src/server/help_test.go
- src/server/list.go
- src/server/server.go
As a follow-up to https://github.com/letsblockit/letsblockit/pull/243, generate list URLs with the `.txt` suffix for adguard compatiblity.
We'll still support the extension-less URL for compatibility of course.
> Add .txt suffix to list download links

- data/filters/youtube-recommendations.yaml
Hides the grid of videos that youtube shows after the video ends.
> youtube-recommendations: add option to hide the endscreen grid

- data/filters/youtube-shorts.yaml
Closes https://github.com/letsblockit/letsblockit/issues/265, rules confirmed to work with the old and new nav menu layouts.
> youtube-shorts: update for new navigation menu markup

- data/filters/google-search-cleanup.yaml
Fixes https://github.com/letsblockit/letsblockit/issues/219 after another layout change.
A new layout was deployed for movies / books / actors, that was completely blocked by the "Hide most rich-content results (images, stories, businesses...) in the web search" option. https://github.com/letsblockit/letsblockit/pull/223 fixed this by looking for the `#kp-wp-tab-overview` element and duplicating the rules for the two general & "cultural works" layout.
Some news results use a similar deeply-nested layout that also creates a false-positive with the rules for the general layout. This PR changes the rules for the general layout, by making them positively match the old layout (with a pretty inefficient but more robust `#rso:has(> div:nth-of-type(6))`), which should make sure new deeply nested …
> google-search-cleanup: fix false-positive on new news layout

- src/users/auth/ory.go
- src/users/auth/ory_test.go
Following Ory's recommendations, starting Kratos flows requires a `POST` request to protect against CSRF attacks.
The login / registration flows are less sensitive than the others, so let's add a `GET` handler alias, to address https://github.com/letsblockit/letsblockit/issues/270
Users can bookmark https://letsblock.it/user/action/loginOrRegistration to get on the login form. If their session is active, they are redirected to the homepage anyway.
> ory: allow GETs on /user/action/loginOrRegistration

- data/filters/youtube-shorts.yaml
Hides that new shelf in the video recommendation sidebar:
> youtube-shorts: hide Shorts shelf in sidebar recommendations

- data/filters/youtube-cleanup.yaml
copyright-notice: the other rule does not exist anymore
<details><summary>Working rule print-screen</summary>
</details> 
<details><summary>NOT working rule print-screen</summary>
</details>
> youtube-cleanup: update copyright-notice rule for new layout

- .github/filter-lint-failed.md
- .github/filter-lint-ok.md
- .github/workflows/filter-lint.yml
New workflow running on PRs changing the `data/filters/` contents. It runs the input validation tests and keeps one comment updated with its output. Hopefully, this will be helpful to contributors by:
- surfacing the failures without requiring to dig into the CI logs
- linking to the syntax documentation, that we'll need to improve over time
> ci: post filter linting output as comment on PRs

- data/filters/youtube-shorts.yaml
Now that shorts are in their separate shelves in the homepage and channel pages, I cannot find any occurrence of use for the rules matching the video duration.
Removing it for both desktop and mobile.
Closes https://github.com/letsblockit/letsblockit/issues/324
> youtube-shorts: remove outdated rules matching by duration

- data/filters/youtube-watched.yaml
Fixes https://github.com/letsblockit/letsblockit/issues/306 and https://github.com/letsblockit/letsblockit/issues/304
The issue is that the homepage rule was not specific enough, and matching one type of video in the channel page. Using the channel rule without the homepage rule would not completely work, but a user setting both rules on could not reproduce the issue.
Duplicate the `ytd-rich-item-renderer` rule for both options, with a specific `page-subtype` filter like we do in other templates.
> youtube-watched: fix use of channel rule without homepage

- data/filters/templates/youtube-shorts.yaml
`:has()` is not yet implemented in browsers, and is currently implemented in javascript, which comes with reduced performance and compatibility. Let's start replacing it with `:upward()` where we can.
Removing the test case for this template, as it has no parameter to test anyway.
> youtube-shorts: improve rule performance

- data/filters/templates/nebula-creators.yaml
Replace the use of `:has()` with `:upward()` for increased performance and compatibility. Use the newly added aria role hints to match on, now most lists are filtered: homepage videos, all videos, creator list.
> nebula-creators: improve rule performance

- data/filters/templates/youtube-search-cleanup.yaml
Closes #338 
Made the template non-configurable for now, if requested we can decouple the two rules with parameters later. No need to mobile rules, as only organic results seem to be shown to mobile devices.
> youtube-search-cleanup: add new template

- data/filters/templates/youtube-video-title.yaml
See https://github.com/letsblockit/letsblockit/issues/347 (Hide Youtube videos by title should look for other separators if possible)
I changed every `~` for `*`.
> youtube-video-title: improve word matching

- flake.nix
- go.mod
- go.sum
- nix/letsblockit.nix
- src/users/prefs.go
We are experimenting with running two VMs for the official instance (Europe & US West coast), while users should be directed to only the closest instance, they might fallback to the other one during rollouts. 
Make sure the instance does not keep outdated user prefs indefinitely. Let's start with a 30 minutes expiration duration, and iterate from there.
> server: expire cached prefs after 30 minutes

- data/filters/templates/youtube-cleanup.yaml
The existing rules don't work with the new youtube layout (not another new one, but the current new one). *Some how never tested this rule before after the change.* 
If you play a video with hashtags - like `https://www.youtube.com/watch?v=llxmTHt5zPs (guitar music)` the hashtags are not shown above the video title, but at the end of the line which shows the date the video got uploaded. 
See:
> youtube-cleanup: update for new hashtag design

- data/filters/templates/youtube-cleanup.yaml
Closes https://github.com/letsblockit/letsblockit/issues/400
Sourced from https://www.reddit.com/r/uBlockOrigin/comments/115f6rz/disable_some_touch_functionality_on_a_full/
> youtube-cleanup: allow to disable swipe actions

- data/filters/templates/url-param-remover.yaml
Addresses https://github.com/orgs/letsblockit/discussions/414
> We could leave it as is, just make the description more explicit about it being a manual way to add rules, not an up-to-date preset. We could add a one-click install of the AdGuard list, now that our domain is in the uBO whilelist for one-click install links.
> url-param-remover: update description to direct users to maintained community lists

- data/filters/templates/google-search-cleanup.yaml
Example search for "b2b product metrics":
The only non-minified stuff I could find in this spaghetti code is the `g-img` element type for the images, that appears in other types of "rich content". Let's match this one and hope we don't create false-positives somewhere else.
> google-search-cleanup: update to match the new "From sources across the web" content

- data/filters/templates/youtube-cleanup.yaml
As per new lay-out YouTube shows additional channel info at the bottom of the video description (example: `https://www.youtube.com/watch?v=UuUVAZHV1qU`).
> youtube-cleanup: Remove channel info at bottom of video description

- data/filters/templates/youtube-mixes.yaml
I could only find radio/mixes if I searched something. 
Regarding the other rule: I could not find radios/mixes on those places in `m.youtube.com`.
> youtube-mixes: Add support for mobile YouTube

- data/filters/templates/youtube-cleanup.yaml
- I tested all the rules and verified that they still work. 
- Not all rules need to be applied on the mobile website of YouTube (`m.youtube.com`)
* Hide the live chat when viewing streams --> is not visible, so no need to hide
* Disable ambient mode --> not available 
* Hide all comments below the video --> is only a button you need to press before you see the comments
> youtube-cleanup: Add support for mobile YouTube

- data/filters/templates/youtube-mixes.yaml
Since you stated in https://github.com/letsblockit/letsblockit/pull/454#issue-1750061231
> Move away from the `:has(` operator and into the `:upward(` one for better performance + match both container classes
And this template had still `:has(` operators, I changed them into `:upward`
> youtube-mixes: improve rule performance

- data/filters/templates/youtube-channel.yaml
Since you stated in https://github.com/letsblockit/letsblockit/pull/454#issue-1750061231
> Move away from the `:has(` operator and into the `:upward(` one for better performance + match both container classes
And this template had still `:has(` operators, I changed them into `:upward`
> youtube-channel: improve rule performance

- data/filters/templates/search-results.yaml
Closes https://github.com/letsblockit/letsblockit/issues/430, check that issue for context.
The Bing rules have been broken for at least two months, due to them adding obfuscation. For these users, my recommendation is to use the dedicated uBlacklist extension instead, as that extension can run javascript to decode the URL, and amortize its filtering cost more easily than we can with uBO rules.
I think there's still room for that template as a "don't install yet another extension" territory for a few hundred domains, but power users will be better served by that dedicated extension.
> search-results: remove Bing support and link to uBlacklist project

- data/filters/templates/youtube-channel.yaml
- data/filters/templates/youtube-mixes.yaml
- data/filters/templates/youtube-shorts.yaml
- data/filters/templates/youtube-upcoming-videos.yaml
- data/filters/templates/youtube-video-title.yaml
The new youtube layout added `ytd-rich-grid-row` elements wrapping the thumbnails. These elements block the reflow when we hide thumbnails, creating gaps in the grid.
This rule uses add the `display: contents` CSS property, that's basically "ignore these elements when computing layout, effectively returning the DOM to a reflowing list of thumbnails.
For ease of use, we're adding this rule to every template that hides thumbnails in the homepage or subscriptions page. Content blockers will transparently de-duplicate that rule when parsing the list.
> youtube: fix gaps in video grids with new layout

- data/filters/templates/youtube-mixes.yaml
- Add a rule for mixes on the homepage. Just removing the `ytm-radio-renderer` does not allow other videos to reflow, so I'm matching the parent `ytm-rich-item-renderer`
- Remove the tests section as we don't have params
> youtube-mixes: add support for mobile youtube (homepage)

- data/filters/templates/youtube-search-cleanup.yaml
Added support for mobile website
Example url: `https://m.youtube.com/results?search_query=shuffle+dance+music+`
The blocked elements are per video and it's not one block with videos. 
The rule I made, is based on the fact that below the channel name is an extra badge (this is different in every language, so mine is Dutch and says  "Gerelateerd" *(Related)*)
Don't know actually why you put a red border around the elements...
PrintScreen
> youtube-search-cleanup: fix the rules to actually hide elements

- data/filters/templates/youtube-cleanup.yaml
Recently I am getting a new button layout for which the current rule don't work.
This fix solves the problem.
to
> youtube-cleanup: update for new layout

- data/filters/templates/youtube-cleanup.yaml
See issue #479 for background info and printscreen. 
At the bottom of video descriptions there is sometimes a section called "chapters" *(name depends on language)* if the video has chapters. Some want this to be removed.
> youtube-cleanup: add option to hide the chapter timeline in the video description box

- data/filters/templates/youtube-cleanup.yaml
> youtube-cleanup: hide floating reaction bar in live chat

- README.md
- data/contributors.json
- data/filters/templates/youtube-cleanup.yaml
- Manually add three new contributors for the ongoing PRs, as https://github.com/all-contributors/cli/issues/359 is not fixed yet 
- Add attribution in the youtube-cleanup template for https://github.com/letsblockit/letsblockit/pull/493
> add new contributors

- src/db/migrations/0010_twitter_remove.sql
The two twitter templates have been deprecated in the previous release, remove them from the DB.
I intentionally didn't enable it in the previous release to allow self-hosted users to rollback without losing data.
> db: remove filter instances for twitter templates

- data/filters/templates/google-search-cleanup.yaml
Fixes https://github.com/letsblockit/letsblockit/issues/500
Both the regular and the alternative `#kp-wp-tab-overview` layouts work with this rule. Tested on these pages:
- https://www.google.com/search?q=time+in+uk (regular layout)
- https://www.google.com/search?q=best+actor+2022 (alternative layout for cultural topics)
> google-search-cleanup: update "People also ask" rule

- data/filters/templates/github-cleanup.yaml
Allow to hide this alert. Disabled by default.
> github-cleanup: allow to hide the "Overwhelmed by notifications?" prompt

- data/filters/templates/youtube-shorts.yaml
Add back search-results since I could reproduce it.
***
Quick question: should we hide the COVID-19 banner, or is that too political to do?
> youtube-shorts: fix regression in search results

- data/filters/templates/youtube-cleanup.yaml
`###super-title` is the oldest rule; I couldn't reproduce it for a long time.
> youtube-cleanup: remove obsolete rule

- data/filters/templates/woolworths-cleanup.yaml
Note: Currently a draft PR as I need to fix the tests.
Add a filter template to cleanup search results on the Woolworths (AU) site.
Can be used to:
- Remove reseller (aka "market partner") results [^1]
- Remove non-product results [^2]
Fixes: https://github.com/letsblockit/letsblockit/issues/496
[^1]: ![SCR-20230717-joxe-2](https://github.com/letsblockit/letsblockit/assets/862951/95c6283a-3325-4856-9e99-bb3fe7ee64b9)
[^2]: ![SCR-20230717-jpsx-2](https://github.com/letsblockit/letsblockit/assets/862951/fbc9c00c-5c0b-4f34-acf7-9fb301e6f18d)
> woolworths-cleanup: add new woolworths (AU) search results cleanup template

- data/filters/templates/youtube-shorts.yaml
In the homepage and subscription pages, the video grid can be interrupted with a partial row. This is where the shorts shelf sits, and it's `ytd-rich-section-renderer` container breaks the reflow.
I'm adding a separate rule for this case, to keep the `www.youtube.com##ytd-rich-shelf-renderer[is-shorts]` rule as wide as possible for future-proofing.
> youtube-shorts: avoid gaps in video grids by hiding the shelf's container

- data/filters/templates/youtube-shorts.yaml
Re-introduce the rule removed in https://github.com/letsblockit/letsblockit/commit/b6c092c178d144e57b768218f46cc8dd203661fa, as this layout is back.
> youtube-shorts: hide individual shorts in recommendation sidebar

- data/filters/templates/youtube-cleanup.yaml
YT has a new layout at my side, which causes the blue clarification box visible again. See `https://www.youtube.com/watch?v=Wp0BJNpEzB4`.  This rule solves it. 
Notice: the other rules still exist in YT source code.
> youtube-cleanup: update rule for channel clarification

- data/filters/templates/google-search-cleanup.yaml
Link used for testing: `https://www.google.com/search?q=remove+people+also+search+for#ip=1`
The rules for `People also ask` also works on mobile versions, but `People also search for` not.  The proposed rule did not give false positives both on the mobile version as on the normal version of google.
> google-search-cleanup: Hides "People also search for" on mobile versions

- data/filters/templates/github-cleanup.yaml
The "For you" feed is non-optional now, so this rule is outdated. Let's remove it to avoid confusion. Also, the feed can be configured now, so it's less obnoxiously bad:
This is safe for existing users: the option will stay in the DB but be unused without error, and deleted the next time the user updates that template's configuration.
> github-cleanup: remove outdated option to hide "For you" feed

- data/filters/templates/youtube-music-cleanup.yaml
If you go to `https://music.youtube.com/moods_and_genres` and click on one off the genres or moods, the page is broken. This PR fixes that problem
> youtube-music-cleanup: fix broken `/moods_and_genres` page

- data/filters/templates/youtube-channel.yaml
Hide videos of certain channels in `https://www.youtube.com/shorts/`.
Although I don't know how useful this rule is, here's a rule for people who still want to watch shorts, but don't want to accidentally come across one from certain YouTube channels.
If you don't think that this is usefull feel free not to merge it.
> youtube-channel: hide videos by channel in the shorts page too

- data/filters/templates/youtube-cleanup.yaml
The element `.modern-sd-container` doesn't exist anymore as element for the description box in `m.youtube.com`, thus making it necessary to make new rules.
Tested on `https://m.youtube.com/watch?v=qgNBB1socTo`.
> youtube-cleanup: update yt music for new lay-out

- data/filters/templates/soundcloud-reposts.yaml
It's "SoundCloud", not "Soundcloud".
> soundcloud-reposts: fix typo

- data/filters/templates/youtube-short-videos.yaml
- data/filters/templates/youtube-video-duration.yaml
https://github.com/letsblockit/letsblockit/issues/621
> youtube-video-duration: filter out videos by their duration

- data/filters/templates/youtube-video-duration.yaml
Fix https://github.com/letsblockit/letsblockit/issues/621#issuecomment-1901822084
```txt
I implemented two rules:
*   Exclude videos shorter than 1 minute: 0:\d\d
*   Exclude videos longer than one hour: 1:\d\d:\d\d|\d\d:\d\d:\d\d
I don't see any short vids on my home page, but this 1h36m video displayed on the home page: https://www.youtube.com/watch?v=701pwm78Q90
```
> youtube-video-duration: fix examples

- data/filters/templates/google-search-cleanup.yaml
Fixes https://github.com/letsblockit/letsblockit/issues/635. Took the opportunity to convert the template to the simple rules format, as it was not making use of handlebars loops.
I kept the comments, as they are useful for maintenance. WDYT about using this `## ` prefix for this kind of comments? We already use the `! ` comment prefix to delineate templates and presets, when rendering the list.
> google-search-cleanup: add option to hide the default search autocomplete options

- data/filters/templates/google-search-cleanup.yaml
Fixes https://github.com/letsblockit/letsblockit/issues/649, lines starting with `# ` are comments, but `## ` leads to a parsing error on some extensions. Let's use `!#`, as any line starting with `!` is parsed as a comment.
> google-search-cleanup: fix comments

- scripts/upgrade-deps.sh
Let's keep upgrading backend deps, but freeze frontend deps. We'll upgrade manually if a CVE were to be published (unlikely given the limited scope of these deps).
> upgrade-deps.sh: stop upgrading frontend deps
