letsblockit/letsblockit

- data/filters/url-param-remover.yaml
Allows removing URL parameters (for example utm_source and utm_medium)
> Create url-param remover filter

- cmd/render/testdata/expected.txt
- src/filters/list.go
- src/filters/list_test.go
- src/server/list_test.go
Fixes https://github.com/xvello/letsblockit/issues/78
> Set the update interval to 1 day (minimum for uBO)

- data/filters/search-results.yaml
Add Bing.com support
Fixes #79
> search-results: add bing support

- data/filters/youtube-shorts.yaml
Updates the description as discussed in https://github.com/xvello/letsblockit/issues/107
> youtube-shorts: update description

- data/filters/youtube-mixes.yaml
> youtube-mixes: add template

- data/filters/youtube-cleanup.yaml
without "comments with certain words", because that was getting to difficult for me at the moment
> youtube-cleanup: hide video hashtags and comments

- data/filters/google-search-cleanup.yaml
> google-search-cleanup: fix missing navigation footer

- cmd/render/README.md
- cmd/server/main.go
- cmd/server/main_test.go
- flake.nix
- scripts/run-server.sh
- src/db/store.go
- src/server/ory.go
- src/server/server.go
- src/server/suite_test.go
Part of work on https://github.com/letsblockit/letsblockit/issues/69 (container releases for self-hosting): 
- reorganize and cleanup the command-line flags for the server
- add environment variable support for them
- update nix packaging to build viable container images we'll release soon
> Rework server command flags, support envvars, add container image

- data/filters/soundcloud-reposts.yaml
- src/filters/repository.go
Add new filter template based on an idea by @krisu5
Closes https://github.com/letsblockit/letsblockit/issues/208
> soundcloud-reposts: add new filter template

- data/filters/youtube-shorts.yaml
Fixes https://github.com/letsblockit/letsblockit/issues/230
After that filter is merged, we'll need to update the other youtube ones.
> youtube-shorts: support mobile layout

- data/filters/youtube-cleanup.yaml
Closes https://github.com/letsblockit/letsblockit/issues/262
> youtube-cleanup: add rule to disable fullscreen on double-click

- data/data.go
- flake.lock
- flake.nix
- nix/letsblockit.nix
- nix/migrate.nix
- nix/ory.nix
- nix/sqlc.nix
Update to the latest nixpkgs release, and go 1.19. Hopefully, should not have any impact on the server or the docker images.
I'll do a second round of QA on the images before tagging the next release.
> upgrade nixpkgs and go

- data/filters/youtube-channel.yaml
A solution for https://github.com/letsblockit/letsblockit/issues/295
> youtube-channel: create template to hide videos from given channels

- src/db/interface.go
- src/db/migrations/0008_schema_cleanups.up.sql
- src/db/models.go
- src/db/qInstances.sql.go
- src/db/qLists.sql.go
- src/db/qStats.sql.go
- src/db/queries/qInstances.sql
- src/db/queries/qLists.sql
- src/db/queries/qStats.sql
- src/server/filters.go
- src/server/filters_test.go
- src/server/list.go
- src/server/list_test.go
- src/server/news_test.go
- src/server/server.go
- src/server/suite_test.go
- src/server/user.go
- src/users/prefs_test.go
- Schema cleanups & renames
- Store timestamps with timezones to avoid any issues if we move countries someday
Automated migration will run on first start. Downgrading will not be supported.
> Miscellaneous DB schema cleanups

- src/server/server.go
Healthcheck is required by fly.io orchestration, let's:
- add a cheap one instead of pinging the homepage
- skip access logs on it to reduce volume
> server: add /_health route with no access log

- src/server/server.go
Reverts letsblockit/letsblockit#357, this creates 404 on the `/` route
> Revert "server: add gzip compression on official instance"

- data/filters/templates/amazon-products.yaml
- data/filters/templates/google-search-cleanup.yaml
- data/filters/templates/linkedin-posts-by-link.yaml
- data/filters/templates/linuxfr-cleanup.yaml
- data/filters/templates/nebula-creators.yaml
- data/filters/templates/search-results.yaml
- data/filters/templates/soundcloud-reposts.yaml
- data/filters/templates/twitter-tweets-by-hashtag.yaml
- data/filters/templates/twitter-tweets-by-user.yaml
- data/filters/templates/url-param-remover.yaml
- data/filters/templates/youtube-channel.yaml
- data/filters/templates/youtube-cleanup.yaml
- data/filters/templates/youtube-mixes.yaml
- data/filters/templates/youtube-recommendations.yaml
- data/filters/templates/youtube-search-cleanup.yaml
- data/filters/templates/youtube-shorts.yaml
- data/filters/templates/youtube-upcoming-videos.yaml
- data/filters/templates/youtube-video-title.yaml
- data/filters/templates/youtube-watched.yaml
- data/pages/list-filters-table.hbs
- go.mod
- go.sum
- nix/letsblockit.nix
- src/filters/repository.go
- src/server/filters_test.go
- src/server/testdata/templates/custom-rules.yaml
- Sort templates by title instead of file name
- Update template titles to start with the target website
- Remove tag pill from template list table
> Misceleanous UX improvements

- src/news/releases.go
- src/server/server.go
Reverts letsblockit/letsblockit#368
> Revert "server: preload github releases on official instances"

- data/filters/templates/youtube-shorts.yaml
Looks like they reverted the icon change. Let's reintroduce it if in changes again.
Reverts letsblockit/letsblockit#376
> Revert "youtube-shorts: update for new navigation icon shape"

- data/filters/templates/youtube-shorts.yaml
Closes https://github.com/letsblockit/letsblockit/issues/389, thanks @SiggyPony for the report!
> youtube-shorts: update for new suggestions layout

- src/server/list.go
- src/server/list_test.go
- src/server/server.go
- src/server/suite_test.go
The overwhelming majority of requests to not present the etag, so let's remove this code to simplify the server.
> server: remove list etag mechanism

- data/filters/templates/google-search-cleanup.yaml
> google-search-cleanup: allow to hide Q&A + Reviews from right-hand pane

- data/filters/templates/youtube-recommendations.yaml
> youtube-recommendations: add rules for mobile version

- data/filters/templates/youtube-channel.yaml
> youtube-channel: add support for mobile website

- data/filters/templates/github-cleanup.yaml
Implements https://github.com/letsblockit/letsblockit/issues/424
> github-cleanup: add new template to declutter the GitHub interface

- data/filters/templates/google-search-cleanup.yaml
As discussed at https://github.com/letsblockit/letsblockit/pull/440#issuecomment-1569834633. 
-  `3DWORX-SA` opened the issue
-  I made the rules and latter on improved them because of a  bug.
> google-search-cleanup: add contributors

- data/filters/templates/youtube-watched.yaml
Solves https://github.com/letsblockit/letsblockit/issues/449
Move away from the `:has(` operator and into the `:upward(` one for better performance + match both container classes
There's other outdated templates to look at, I'll open one PR per template, for the changelog.
> youtube-watched: update for new layout

- data/filters/templates/fandom-cleanup.yaml
Fixes https://github.com/letsblockit/letsblockit/issues/531 by overriding the offending style
> fandom-cleanup: fix background cosmetic issue

- data/filters/templates/fandom-cleanup.yaml
Fixes #550
I choose to set default checkbox on false as maybe some people want this popup to see
> Update fandom-cleanup: Add rule to block `age gate`

- data/filters/templates/youtube-music-cleanup.yaml
Test link: `https://music.youtube.com/watch?v=dopf-_6KkOQ`
Make sure autoplay is turned on.
> youtube-music-cleanup: hide videos of channels when player is open

- data/filters/templates/hackernews-cleanup.yaml
- data/filters/templates/youtube-recommendations.yaml
`youtube-watched.yaml` ?
Should / Can not be converted, right?
> Convert to new template format

- data/filters/templates/youtube-recommendations.yaml
When viewing a playlist like `https://www.youtube.com/playlist?list=PLqtNdfVEaz0BOlPXbTyA2qIUHGNn661OC` at the bottom you see some `Recommendations`
> youtube-recommendations: Hide suggestions in playlist

- data/filters/templates/youtube-watched.yaml
- src/db/migrations/0012_youtube-watched_add-channel.up.sql
> youtube-watched: seperate rules for channel and subscription pages
